name: CI Security

on:
 push:
  branches: [main]

jobs:
 seguridad:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: Instalar dependencias
    run: npm install

  - name: Ejecutar pruebas
    run: npm test

  - name: Analisis secretos Gitleaks
    uses: gitleaks/gitleaks-action@v2

  - name: Analisis vulnerabilidades Trivy
    uses: aquasecurity/trivy-action@master